{
 "title": "Syncthing Exporter 0.3.0",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deviceID",
    "label": "deviceID",
    "query": {
     "query": "syncthing_rest_system_connections_remote_device_connection_info"
    }
   },
   {
    "name": "clientVersion",
    "query": {
     "query": "syncthing_rest_system_connections_remote_device_connection_info"
    }
   },
   {
    "name": "crypto",
    "label": "crypto",
    "query": {
     "query": "syncthing_rest_system_connections_remote_device_connection_info"
    }
   },
   {
    "name": "myClientLongVersion",
    "label": "myClientLongVersion",
    "query": {
     "query": "syncthing_rest_svc_report_node_info"
    }
   },
   {
    "name": "folderID",
    "label": "folderID",
    "query": {
     "query": "syncthing_rest_db_status_sequence"
    }
   },
   {
    "name": "state",
    "query": {
     "query": "syncthing_rest_db_status_sequence"
    }
   },
   {
    "name": "stateChanged",
    "query": {
     "query": "syncthing_rest_db_status_sequence"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_node_info"
    }
   ]
  },
  {
   "title": "Node memory size in megabytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_memory_size"
    }
   ]
  },
  {
   "title": "Total bytes transmitted from device",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_total_out_bytes_total"
    }
   ]
  },
  {
   "title": "Total data in megabytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_total_data_in_MB"
    }
   ]
  },
  {
   "title": "Total bytes received to device",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_total_in_bytes_total"
    }
   ]
  },
  {
   "title": "Number of node CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_num_cpu"
    }
   ]
  },
  {
   "title": "Syncthing uptime in seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_uptime"
    }
   ]
  },
  {
   "title": "Total number of files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_total_files"
    }
   ]
  },
  {
   "title": "My client version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_node_info{}"
    }
   ]
  },
  {
   "title": "SHA256 Performance value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_sha256_performance",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory usage by syncthc in MB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "syncthing_rest_svc_report_memory_usage_mb",
     "legendFormat": "{{syncthing_data}}"
    }
   ]
  },
  {
   "title": "Information of the connection with remote device",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_connection_info{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Is sync paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_is_paused{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Syncthing client version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_connection_info{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Crypto configuration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_connection_info{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Total bytes transmitted to remote device",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_out_bytes_total{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Total bytes received from remote device",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_system_connections_remote_device_in_bytes_total{deviceID=\"$deviceID\"}"
    }
   ]
  },
  {
   "title": "Items by folderID",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "syncthing_rest_db_status_global_total_items{folderID=\"$folderID\"}",
     "legendFormat": "Global total items"
    },
    {
     "expr": "syncthing_rest_db_status_local_total_items{folderID=\"$folderID\"}",
     "legendFormat": "Local total items"
    },
    {
     "expr": "syncthing_rest_db_status_need_total_items{folderID=\"$folderID\"}",
     "legendFormat": "Need total items"
    },
    {
     "expr": "syncthing_rest_db_status_insync_files{folderID=\"$folderID\"}",
     "legendFormat": "Insync Files"
    }
   ]
  },
  {
   "title": "Folder state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_db_status_sequence{folderID=\"$folderID\"}"
    }
   ]
  },
  {
   "title": "Folder state changed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "syncthing_rest_db_status_sequence{folderID=\"$folderID\"}"
    }
   ]
  }
 ]
}